services:
  database:
    image: mariadb:10.11
    environment:
      MARIADB_DATABASE: briefed_v2
      MARIADB_USER: briefed
      MARIADB_PASSWORD: briefed
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - database_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  database_data:
